controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

# config/routes.yaml

app_home:
    path: /
    controller: App\Controller\AccueilController::index

app_plats:
    path: /plats
    controller: App\Controller\AccueilController::listePlats

app_plats_categorie:
    path: /plats/{categorie_id}
    controller: App\Controller\AccueilController::platsParCategorie

app_categories:
    path: /categories
    controller: App\Controller\AccueilController::listeCategories

app_panier:
    path: /panier
    controller: App\Controller\PanierController::index

app_commande:
    path: /commande
    controller: App\Controller\CommandeController::index

app_contact:
    path: /contact
    controller: App\Controller\ContactController::index

app_login:
    path: /login
    controller: App\Controller\SecurityController::login
    
plat_details:
    path: '/plat/{id}'
    controller: 'App\Controller\AccueilController::platDetails'

ajouter_au_panier:
    path: /ajouter-au-panier/{plat}
    controller: App\Controller\PanierController::ajouterAuPanier

retirer_du_panier:
    path: /retirer-du-panier/{id}
    controller: App\Controller\PanierController::remove

commande_afficher_formulaire:
    path: '/commande/afficher-formulaire'
    controller: 'App\Controller\CommandeController::afficherFormulaire'

valider_commande:
    path: '/valider-commande'
    controller: 'App\Controller\CommandeController::validerCommande'
    methods: ['POST']






    

